export interface StudyGroup {
  id?: string; // Will be auto-generated by Firestore
  title: string;
  subject: string;
  description: string;
  location: {
    name: string;
    latitude: number;
    longitude: number;
  };
  dateTime: Date;
  maxParticipants: number;
  createdBy: string; // User ID
  createdAt: Date;
  participants: string[]; // Array of user IDs
  tags?: string[];
}
